### ISSUE TITLE
A question about prognosis

### ISSUE THREAD

**Issue by ourSherlock** [slobentanzer/stroke-trf#1]
I'm sorry for such a bold inquiry, but I really want to know why the prognosis standard is three months' mRs minus discharged mRs, which has troubled me for a long time. I would be grateful if you could reply.

**Comment by slobentanzer** [comment]
Thanks for your question; I could use some more background though. What do you mean by "prognosis standard"? Are you referring to the contrast we used?

**Comment by ourSherlock** [comment]
> Thanks for your question; I could use some more background though. What do you mean by "prognosis standard"? Are you referring to the contrast we used?

I'm sorry I didn't explain my problem clearly. I see that the definition of improvement or deterioration recovery is based on Delta_ MRS, Delta_ MRS is based on MRS_ 3month - MRS_ Discharge, I haven't seen such a definition in other articles.I want to know Why is Delta_MRS defined this way? Thank you for your time.

**Comment by slobentanzer** [comment]
Hi @ourSherlock, sorry for the delay. I have a response from my co-author now, here it is:

> With delta mRS we initally aimed to measure the change between the mRS (modified Rankin Scale, see Swieten et al. Stroke 1988 and e.g. Banks&Marotta Stroke 2017 - a score widely used to asses the degree of disability in stroke patients) at discharge from the hospital and then at 3 months follow-up. As higher score is linked with a higher degree of disability, a negative value would implicate functional deterioration, a positive one - an improvement. Please note that in the end we did not include the outcome assessment in our investigations, so this parameter was not used in our study. 

Feel free to specify if something else is unclear.

**Comment by ourSherlock** [comment]
Thank you very much for your reply, which will be very helpful to me!
